### PR TITLE
Added NuMicro M0 chip

### PR DESCRIPTION
**Pull request by runfalk**
Hi, I just tested your tool with a Ducky One 2 Mini (2020) and I have added that particular microcontroller. Thanks for this tool!

### CODE REVIEW

**Comment by elfmimi** [comment]
@runfalk I have `cargo publish`-ed 0.7.1 .
I'm curious. Are you working on a project to port QMK to Ducky One2Mini 2061st?

**Comment by runfalk** [comment]
Thanks! No, I'm planning to extract the current firmware from the official tool and then flash it with your program. I want to use it to restore the original firmware if I screw up.

My plan was to write a custom firmware in Rust, but I haven't started yet. I need to figure out how the PCB is wired first. If that works I need to write a HAL for the microcontroller. And then I can think about a custom firmware 😂.

**Comment by elfmimi** [comment]
Nice. I'm thinking of doing similar for my own Rust keyboard firmware. 😃

**Comment by runfalk** [comment]
Which keyboard do you have?

**Comment by elfmimi** [comment]
Z70 Pro from Melgeek (former 0.01).
Which is using NUC123LD4AN0.

**Pull request merged**
